const express=require('express');const http=require('http');const {Server}=require('socket.io');const crypto=require('crypto');
const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.static('public'));
app.get('*',(_,res)=>res.sendFile(__dirname+'/public/index.html'));
const rooms=new Map();
const items=[
['صندوق غامض 🎁','لا أحد يعرف ما بداخله… قد تربح ثروة أو تخسر كل شيء!'],['سيارة فاخرة 🚗','هدية افتراضية ضخمة، لكن سعرها الحقيقي مجهول.'],['مفتاح القصر 🗝️','هل يستحق أن تدفع كل رصيدك؟'],['كنز القراصنة 💰','قد يكون كنزًا… وقد يكون فخًا.'],['بطاقة ×2 ⚡','تضاعف مكسبك من الجولة القادمة.'],['درع 🛡️','يحميك من أول عملية سرقة.'],['صندوق الذهب 🪙','جائزة مضمونة بين 200 و700 نقطة.'],['قنبلة 💣','المشتري قد يحصل على قوة خطيرة!'],['تاج الملك 👑','صاحبها يحصل على مكافأة خاصة.'],['بوابة الحظ 🎲','الحظ وحده يقرر مصيرك.'],['سرقة كبرى 🕵️','قد تسرق جزءًا من رصيد منافس.'],['صندوق الحظ 🍀','جائزة عشوائية… لا يوجد رجوع.']];
function code(){let c;do c=crypto.randomInt(0,10000).toString().padStart(4,'0');while(rooms.has(c));return c}
function pub(r){return {code:r.code,phase:r.phase,round:r.round,totalRounds:r.totalRounds,item:r.item,bid:r.bid,bidder:r.bidder,endsAt:r.endsAt,players:[...r.players.values()].map(p=>({id:p.id,name:p.name,balance:p.balance,connected:p.connected,shield:p.shield})),winner:r.winner,message:r.message}}
function newRoom(){return {code:code(),phase:'waiting',round:0,totalRounds:10,item:null,bid:0,bidder:null,endsAt:0,players:new Map(),winner:null,message:'',timer:null}}
function startRound(r){if(r.players.size<2)return;r.round++;if(r.round>r.totalRounds){r.phase='finished';r.message='انتهت المزاد!';return}let it=items[crypto.randomInt(0,items.length)];r.item={name:it[0],desc:it[1]};r.bid=0;r.bidder=null;r.winner=null;r.message='المزاد مفتوح!';r.phase='auction';r.endsAt=Date.now()+15000;clearTimeout(r.timer);r.timer=setTimeout(()=>finishRound(r),15000);io.to(r.code).emit('state',pub(r))}
function finishRound(r){if(!rooms.has(r.code))return;if(r.bidder){let p=r.players.get(r.bidder);if(p){let cost=r.bid;p.balance-=cost;r.winner={id:p.id,name:p.name,cost};if(r.item.name.includes('×2'))p.double=true;if(r.item.name.includes('درع'))p.shield=true;r.message=`${p.name} فاز بالمزاد مقابل ${cost} نقطة!`;}}
else r.message='لا أحد فاز بالجولة!';r.phase='result';io.to(r.code).emit('state',pub(r));setTimeout(()=>{if(rooms.has(r.code))startRound(r)},3500)}
io.on('connection',s=>{
 s.on('room:create',({name}={})=>{let r=newRoom();rooms.set(r.code,r);s.data.role='display';s.data.code=r.code;s.join(r.code);s.emit('room:created',{code:r.code});io.to(r.code).emit('state',pub(r))});
 s.on('room:join',({code,name}={})=>{code=String(code||'').replace(/\D/g,'').padStart(4,'0').slice(-4);let r=rooms.get(code);if(!r)return s.emit('errorMsg','رمز الغرفة غير صحيح');if(r.phase==='finished')return s.emit('errorMsg','هذه الغرفة انتهت');if(r.players.size>=12)return s.emit('errorMsg','الغرفة ممتلئة');let id=s.id;r.players.set(id,{id,name:String(name||'لاعب').slice(0,18),balance:1000,connected:true,shield:false,double:false});s.data.role='player';s.data.code=code;s.join(code);s.emit('joined',{id,code});io.to(code).emit('state',pub(r));if(r.phase==='waiting'&&r.players.size>=2)setTimeout(()=>{if(r.phase==='waiting')startRound(r)},1200)});
 s.on('bid',({amount}={})=>{let r=rooms.get(s.data.code),p=r?.players.get(s.id);if(!r||s.data.role!=='player'||r.phase!=='auction'||!p)return;let n=Math.floor(Number(amount));if(!Number.isFinite(n)||n<=r.bid||n>p.balance)return s.emit('errorMsg','المزايدة يجب أن تكون أعلى من السعر الحالي وضمن رصيدك');r.bid=n;r.bidder=s.id;io.to(r.code).emit('state',pub(r))});
 s.on('disconnect',()=>{let r=rooms.get(s.data.code);if(!r)return;if(s.data.role==='player'){let p=r.players.get(s.id);if(p)p.connected=false}io.to(r.code).emit('state',pub(r))});
});
server.listen(process.env.PORT||3000);
